using shellcheck to remove warns on the code

diff --git a/tomatoshell b/tomatoshell
--- a/tomatoshell
+++ b/tomatoshell
@@ -37,9 +37,9 @@ write_to_log() {
 
 
 total_hours_used() {
-    printf "$YELLOW Total hours spent focused: $FIN"
-    awk -F ',' '{sum+=$2 * $3;} END{printf "%d", int(sum / 3600);}' $LOG
-    printf "h ${TOMATO}${FACE}\n"
+   printf "%s Total hours spent focused: %s" "$YELLOW" "$FIN"
+   awk -F ',' '{sum+=$2 * $3;} END{printf "%d", int(sum / 3600);}' "$LOG"
+   printf "h %s%s\n" "$TOMATO" "$FACE"
 }
  
 
@@ -66,7 +66,7 @@ find_sound_system() {
 play_alarm() {
     # when session is finished, start the alarm
     printf "Press 's' to stop alarm"
-    [ $1 -eq -1 ] && echo " and start next session" || echo ""
+    (( $1 == -1 )) && echo " and start next session" || echo ""
 
     process_name="tomatoshell_alarm"
 
@@ -97,7 +97,7 @@ display_countdown() {
         # sleeping for one second between each print to stdout uses less cpu power, but will
         # make the countdown have a discrepency of 1s which is negligable.
         print_offset=10
-        $FIGLET && clear && printf "%*s\n" $(((${#msg}+$COLUMNS+$print_offset)/2)) "$msg" \
+        $FIGLET && clear && printf "%*s\n" $(((${#msg} + COLUMNS + print_offset)/2)) "$msg" \
         && echo -ne "$(date -u --date @$((start - $(date +%s))) +%M:%S)\r" | figlet -c -t ||
         echo -ne "${CYAN}${R_ARROW} $YELLOW $(date -u --date @$((start - $(date +%s))) +%M:%S)$FIN  ${TOMATO}\r"
 
@@ -108,34 +108,39 @@ display_countdown() {
 
 
 countdown() {
-    time=$1
-    session_number=$2
-    msg="${TOMATO} Time left of session $session_number/$SESSIONS:${TOMATO}"
-    [ $session_number -eq -1 ] && msg="${TOMATO} Time left of break:${TOMATO}"
+   session_number="$2"
+   msg="${TOMATO} Time left of session $session_number/$SESSIONS:${TOMATO}"
+   (( session_number == -1 )) && msg="${TOMATO} Time left of break:${TOMATO}"
 
-    # date in seconds when countdown will end
-    start=$(($(date +%s) + $1)); 
+   # date in seconds when countdown will end
+   start=$(( $(date +%s) + $1 ));
 
-    display_countdown $start
-    clear
+   display_countdown "$start"
+   clear
 
-    [ $session_number -ne -1 ] && notify-send -t 10000 -u "normal" "Session number $session_number finished"
+   (( session_number != -1 )) && notify-send -t 10000 -u "normal" "Session number $session_number finished"
     
-    # message when session is finished
-    if $FIGLET
-    then
-        [ $session_number -ne -1 ] && figlet -c -t "Session $session_number/$SESSIONS finished" || figlet -c -t "Break finished"
-    else
+   # message when session is finished
+   if FIGLET; then
+      if (( session_number != -1 )); then
+         figlet -c -t "Session $session_number / $SESSIONS finished"
+      else
+         figlet -c -t "Break finished"
+      fi
+   else
+      if (( session_number != -1 )); then
+         echo -e "${GREEN}Session $session_number / $SESSIONS finished$FIN"
+      else
+         echo -e "${GREEN}Break finished$FIN"
+      fi
+   fi
 
-        [ $session_number -ne -1 ] && echo -e ""$GREEN"Session $session_number/$SESSIONS finished$FIN" || echo -e "$GREEN""Break finished$FIN"
-    fi
+   # turn on keypress so we can receive input from user as to when to stop the alarm
+   stty echo
+   play_alarm "$session_number"
+   stty -echo
 
-    # turn on keypress so we can receive input from user as to when to stop the alarm
-    stty echo
-    play_alarm "$session_number"
-    stty -echo
-
-    return 0
+   return 0
 }
 
 
@@ -147,35 +152,38 @@ exit_p() {
     # turn on keyboard input again
     stty echo
 
-    echo -e ""$RED"\nexiting$FIN"
-    exit $1
+    echo -e "${RED}\nexiting$FIN"
+    exit 0
 }
 
 
 main() {
-    find_sound_system
+   find_sound_system
 
-    # when SIGINT is received, exit
-    trap "exit_p" 2
+   # when SIGINT is received, exit
+   trap "exit_p" 2
 
-    # turn off keyboard input and cursor
-    stty -echo
-    tput civis
+   # turn off keyboard input and cursor
+   stty -echo
+   tput civis
 
-    # convert time and delay to from minutes to seconds
-    # have to divide by 1 to always get integer result
-    TIME=$(echo "($TIME * 60)/1" | bc)
-    DELAY=$(echo "($DELAY * 60)/1" | bc)
+   # convert time and delay to from minutes to seconds
+   # have to divide by 1 to always get integer result
+   TIME=$(echo "($TIME * 60)/1" | bc)
+   DELAY=$(echo "($DELAY * 60)/1" | bc)
 
-    for ((i = 1; i <= $SESSIONS; i++))
-    do
-        clear
-        echo "Time left of session $i/$SESSIONS:"
-        countdown $TIME $i
+   for ((i = 1; i <= SESSIONS; i++)); do
+      clear
+      echo "Time left of session $i/$SESSIONS:"
+      countdown "$TIME" "$i"
 
-        # don't want to have a break after last session
-        [ $i -ne $SESSIONS ] &&  clear && echo "Time left of break:" && countdown $DELAY -1
-    done
+      # don't want to have a break after last session
+      if (( i != SESSIONS )); then
+         clear
+         echo "Time left of break:"
+         countdown "$DELAY" -1
+      fi
+   done
 }
 
 
@@ -205,7 +213,7 @@ do
                 FIGLET=true
             else
                 FIGLET=false
-                echo -e ""$RED"ERROR$FIN: argument '-f' was given, but figlet is not installed"
+                echo -e "${RED}ERROR${FIN}: argument '-f' was given, but figlet is not installed"
                 echo "Starting without figlet in 3 seconds"
                 # maybe add a keypress to start regardless
                 sleep 3
@@ -226,4 +234,4 @@ do
 done
 
 main
-exit_p 0
+exit_p
